name: Publish Lim Server Multi-Arch

on:
  push:
    branches: [ "master" ]
    paths:
      - 'limserver/**'
      - '.github/workflows/publish-server.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        # Это позволяет собирать образы для ARM64 на обычных серверах Intel
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        # Это включает поддержку многоархитектурных сборок
        uses: docker/setup-buildx-action@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Minified Jar
        run: ./gradlew :limserver:minifyJar

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repo name
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build and push Multi-Arch Image
        uses: docker/build-push-action@v5
        with:
          context: ./limserver
          # Указываем обе архитектуры: CHR и ARM64 роутеры
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME }}:latest
            ghcr.io/${{ env.REPO_NAME }}:${{ github.sha }}
